[build]
  command = "npm cache clean --force && rm -rf node_modules && npm install && npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[build.environment]
  NODE_VERSION = "18"
  REACT_APP_API_KEY = "2ec3658520171cd1960bc9e518549a6c"
  REACT_APP_API_URL = "https://api.openweathermap.org/data/2.5/"
  CI = "1"
  GENERATE_SOURCEMAP = "0" 