[build]
  command = "npm run build"
  publish = "build"
  base = "weather"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  REACT_APP_API_KEY = "2ec3658520171cd1960bc9e518549a6c"
  REACT_APP_API_URL = "https://api.openweathermap.org/data/2.5"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps" 